using System;
using System.Collections.Generic;
using System.Text;

namespace SolutionNorSolutionPort.BusinessLogicLayer {
    public partial class DatabaseManager {
        void InitReferenceLanguageSwitch(
            int majorNumber,
            int minorNumber
            ) {

            int sequence = 0;

            scripts.Add(lastScript = new DatabaseScript {
                DatabaseVersion = new DatabaseVersion { MajorNumber = majorNumber, MinorNumber = minorNumber, SequenceNumber = sequence++, DateTime = new DateTime(2019, 02, 04) },
                ScriptNumber = this.scriptNumber++,
                Name = "LanguageSwitchtoNorwegian",
                Description = "Language Switch to Norwegian",
                #region script ( *** )
                DatabaseScriptBatch = new DatabaseScriptBatch {
                    Script = @"
update address_type_ref set address_type_name = 'Office' where address_type_rcd = 'Office'
update address_type_ref set address_type_name = 'Primære' where address_type_rcd = 'Primary'
update address_type_ref set address_type_name = 'Privat' where address_type_rcd = 'Private'
update aircraft_body_ref set aircraft_body_name = 'Smal kropp' where aircraft_body_rcd = 'NB'
update aircraft_body_ref set aircraft_body_name = 'Bred Body' where aircraft_body_rcd = 'WB'
update aircraft_compartment_type_ref set aircraft_compartment_type_name = 'Hoved Last' where aircraft_compartment_type_rcd = 'MCD'
update aircraft_compartment_type_ref set aircraft_compartment_type_name = 'Passasjer sone A' where aircraft_compartment_type_rcd = 'PZA'
update aircraft_compartment_type_ref set aircraft_compartment_type_name = 'Passasjer sone B' where aircraft_compartment_type_rcd = 'PZB'
update aircraft_compartment_type_ref set aircraft_compartment_type_name = 'Passasjer sone C' where aircraft_compartment_type_rcd = 'PZC'
update aircraft_configuration_ref set aircraft_configuration_name = 'Frakte fly' where aircraft_configuration_rcd = 'CA'
update aircraft_configuration_ref set aircraft_configuration_name = 'Kombi fly' where aircraft_configuration_rcd = 'COA'
update aircraft_configuration_ref set aircraft_configuration_name = 'Passasjerfly' where aircraft_configuration_rcd = 'PA'
update aircraft_document_type_ref set aircraft_document_type_name = 'Farbare sertifikat' where aircraft_document_type_rcd = 'AC'
update aircraft_identifier_type_ref set aircraft_identifier_type_name = 'Institutt for transport sertifiserings kode' where aircraft_identifier_type_rcd = 'DOTCC'
update aircraft_identifier_type_ref set aircraft_identifier_type_name = 'Avdeling for transport enhetskode' where aircraft_identifier_type_rcd = 'DOTEC'
update aircraft_identifier_type_ref set aircraft_identifier_type_name = 'Federal Airport Association kode' where aircraft_identifier_type_rcd = 'FAA'
update aircraft_identifier_type_ref set aircraft_identifier_type_name = 'Internasjonale flyselskaps transport tilknytnings kode' where aircraft_identifier_type_rcd = 'IATA'
update aircraft_identifier_type_ref set aircraft_identifier_type_name = 'International Civil Aviation Organization kode' where aircraft_identifier_type_rcd = 'ICAO'
update aircraft_identifier_type_ref set aircraft_identifier_type_name = 'Serienummer for produsent' where aircraft_identifier_type_rcd = 'MSN'
update aircraft_identifier_type_ref set aircraft_identifier_type_name = 'Registrering koden' where aircraft_identifier_type_rcd = 'RG'
update aircraft_type_ref set aircraft_type_name = 'Airbus A300-600' where aircraft_type_rcd = 'Airbus A300-600'
update aircraft_type_ref set aircraft_type_name = 'Airbus A310' where aircraft_type_rcd = 'Airbus A310'
update aircraft_type_ref set aircraft_type_name = 'Airbus A318' where aircraft_type_rcd = 'Airbus A318'
update aircraft_type_ref set aircraft_type_name = 'Airbus A319' where aircraft_type_rcd = 'Airbus A319'
update aircraft_type_ref set aircraft_type_name = 'Airbus A320' where aircraft_type_rcd = 'Airbus A320'
update aircraft_type_ref set aircraft_type_name = 'Airbus A321' where aircraft_type_rcd = 'Airbus A321'
update aircraft_type_ref set aircraft_type_name = 'Airbus A330-200' where aircraft_type_rcd = 'Airbus A330-200'
update aircraft_type_ref set aircraft_type_name = 'Airbus A330-300' where aircraft_type_rcd = 'Airbus A330-300'
update aircraft_type_ref set aircraft_type_name = 'Airbus A340-200' where aircraft_type_rcd = 'Airbus A340-200'
update aircraft_type_ref set aircraft_type_name = 'Airbus A340-300' where aircraft_type_rcd = 'Airbus A340-300'
update aircraft_type_ref set aircraft_type_name = 'Airbus A340-500' where aircraft_type_rcd = 'Airbus A340-500'
update aircraft_type_ref set aircraft_type_name = 'Airbus A340-600' where aircraft_type_rcd = 'Airbus A340-600'
update aircraft_type_ref set aircraft_type_name = 'Airbus A350-800' where aircraft_type_rcd = 'Airbus A350-800'
update aircraft_type_ref set aircraft_type_name = 'Airbus A350-900' where aircraft_type_rcd = 'Airbus A350-900'
update aircraft_type_ref set aircraft_type_name = 'Airbus A350-900r' where aircraft_type_rcd = 'Airbus A350-900R'
update aircraft_type_ref set aircraft_type_name = 'Airbus A380' where aircraft_type_rcd = 'Airbus A380'
update airline_identifier_type_ref set airline_identifier_type_name = 'Flyselskapet koden kort' where airline_identifier_type_rcd = 'AC2'
update airline_identifier_type_ref set airline_identifier_type_name = 'Flyselskapets kode Long' where airline_identifier_type_rcd = 'AC3'
update airline_identifier_type_ref set airline_identifier_type_name = 'Institutt for transport sertifiserings kode' where airline_identifier_type_rcd = 'DOTCC'
update airline_identifier_type_ref set airline_identifier_type_name = 'Avdeling for transport enhetskode' where airline_identifier_type_rcd = 'DOTEC'
update airline_identifier_type_ref set airline_identifier_type_name = 'Internasjonale flyselskaps transport tilknytnings kode' where airline_identifier_type_rcd = 'IATA'
update airline_identifier_type_ref set airline_identifier_type_name = 'Den internasjonale organisasjonen for sivil luftfart' where airline_identifier_type_rcd = 'ICAO'
update airline_type_ref set airline_type_name = 'Planlagt transportør' where airline_type_rcd = 'SC'
update airport_identifier_type_ref set airport_identifier_type_name = 'Flyplasskode tre' where airport_identifier_type_rcd = 'AC3'
update airport_identifier_type_ref set airport_identifier_type_name = 'Flyplasskode fire' where airport_identifier_type_rcd = 'AC4'
update airport_identifier_type_ref set airport_identifier_type_name = 'Federal Airport Association kode' where airport_identifier_type_rcd = 'FAA'
update airport_identifier_type_ref set airport_identifier_type_name = 'Internasjonale flyselskaps transport tilknytnings kode' where airport_identifier_type_rcd = 'IATA'
update airport_identifier_type_ref set airport_identifier_type_name = 'Den internasjonale organisasjonen for sivil luftfart' where airport_identifier_type_rcd = 'ICAO'
update airport_type_ref set airport_type_name = 'Sivile flyplass' where airport_type_rcd = 'CA'
update booking_document_type_ref set booking_document_type_name = 'Eksterne system rådata' where booking_document_type_rcd = 'ESRD'
update booking_document_type_ref set booking_document_type_name = 'Teletype' where booking_document_type_rcd = 'TTY'
update booking_event_type_ref set booking_event_type_name = 'Booking bekreftet' where booking_event_type_rcd = 'BC'
update booking_event_type_ref set booking_event_type_name = 'Booking epost sendt' where booking_event_type_rcd = 'BES'
update booking_event_type_ref set booking_event_type_name = 'Bestilling på vent' where booking_event_type_rcd = 'BH'
update booking_event_type_ref set booking_event_type_name = 'Bestilling re-booket' where booking_event_type_rcd = 'BR'
update booking_event_type_ref set booking_event_type_name = 'Bestilling Split' where booking_event_type_rcd = 'BS'
update booking_event_type_ref set booking_event_type_name = 'Bestilling avbrutt' where booking_event_type_rcd = 'CA'
update booking_event_type_ref set booking_event_type_name = 'Bestilling opprettet' where booking_event_type_rcd = 'CRE'
update booking_event_type_ref set booking_event_type_name = 'Bestilling oppdatert' where booking_event_type_rcd = 'UPD'
update booking_identifier_type_ref set booking_identifier_type_name = 'Bestillingsnummer' where booking_identifier_type_rcd = 'BN'
update booking_identifier_type_ref set booking_identifier_type_name = 'Registrer Locator' where booking_identifier_type_rcd = 'RL'
update booking_identifier_type_ref set booking_identifier_type_name = 'Sender Locator' where booking_identifier_type_rcd = 'SL'
update booking_identifier_type_ref set booking_identifier_type_name = 'Turoperatør Locator' where booking_identifier_type_rcd = 'TOL'
update booking_passenger_event_type_ref set booking_passenger_event_type_name = 'Bordet' where booking_passenger_event_type_rcd = 'BOA'
update booking_passenger_event_type_ref set booking_passenger_event_type_name = 'Checkin' where booking_passenger_event_type_rcd = 'CIFS'
update booking_passenger_event_type_ref set booking_passenger_event_type_name = 'Checkout' where booking_passenger_event_type_rcd = 'COFS'
update booking_passenger_event_type_ref set booking_passenger_event_type_name = 'Avlastede' where booking_passenger_event_type_rcd = 'OL'
update booking_passenger_event_type_ref set booking_passenger_event_type_name = 'Ticketed' where booking_passenger_event_type_rcd = 'TI'
update booking_passenger_event_type_ref set booking_passenger_event_type_name = 'Un-ticketed' where booking_passenger_event_type_rcd = 'UTI'
update booking_source_ref set booking_source_name = 'Byrå' where booking_source_rcd = 'AG'
update booking_source_ref set booking_source_name = 'Internt system' where booking_source_rcd = 'IS'
update booking_source_ref set booking_source_name = 'Turoperatør' where booking_source_rcd = 'TO'
update booking_source_ref set booking_source_name = 'Teletype' where booking_source_rcd = 'TTY'
update client_event_type_ref set client_event_type_name = 'Innledning Mail bekreftet' where client_event_type_rcd = 'IMC'
update client_event_type_ref set client_event_type_name = 'Pakkepost sendt' where client_event_type_rcd = 'PMS'
update client_event_type_ref set client_event_type_name = 'Pakke bestilt' where client_event_type_rcd = 'PO'
update client_event_type_ref set client_event_type_name = 'Pakke nettsted vist' where client_event_type_rcd = 'PSV'
update client_event_type_ref set client_event_type_name = 'Sendt Introduksjons post' where client_event_type_rcd = 'SIM'
update client_type_ref set client_type_name = 'Business' where client_type_rcd = 'B'
update client_type_ref set client_type_name = 'Privat' where client_type_rcd = 'P'
update contact_method_ref set contact_method_name = 'Telefon, arbeid' where contact_method_rcd = 'Business'
update contact_method_ref set contact_method_name = 'Email' where contact_method_rcd = 'Email'
update contact_method_ref set contact_method_name = 'Faks' where contact_method_rcd = 'Fax'
update contact_method_ref set contact_method_name = 'Privat telefon' where contact_method_rcd = 'Home'
update contact_method_ref set contact_method_name = 'Mobile' where contact_method_rcd = 'Mobile'
update contact_method_ref set contact_method_name = 'Mobile MMS' where contact_method_rcd = 'MobileMMS'
update contact_method_ref set contact_method_name = 'Mobil SMS' where contact_method_rcd = 'MobileSMS'
update contact_method_ref set contact_method_name = 'Telefon (internasjonal)' where contact_method_rcd = 'PhoneI'
update contact_method_ref set contact_method_name = 'Telefon (lokal)' where contact_method_rcd = 'PhoneL'
update date_time_type_ref set date_time_type_name = 'Faktisk ankomst' where date_time_type_rcd = 'AA'
update date_time_type_ref set date_time_type_name = 'Aktivert' where date_time_type_rcd = 'AC'
update date_time_type_ref set date_time_type_name = 'Faktisk avgang' where date_time_type_rcd = 'AD'
update date_time_type_ref set date_time_type_name = 'Adl' where date_time_type_rcd = 'ADL'
update date_time_type_ref set date_time_type_name = 'Avansert passasjer informasjons system' where date_time_type_rcd = 'APIS'
update date_time_type_ref set date_time_type_name = 'Bestilling stengt' where date_time_type_rcd = 'BC'
update date_time_type_ref set date_time_type_name = 'Bestilling åpen' where date_time_type_rcd = 'BO'
update date_time_type_ref set date_time_type_name = 'Boarding stengt' where date_time_type_rcd = 'BOAC'
update date_time_type_ref set date_time_type_name = 'Boarding åpen' where date_time_type_rcd = 'BOAO'
update date_time_type_ref set date_time_type_name = 'Avbrutt' where date_time_type_rcd = 'CA'
update date_time_type_ref set date_time_type_name = 'Innsjekking stengt' where date_time_type_rcd = 'CC'
update date_time_type_ref set date_time_type_name = 'Sjekk inn åpen' where date_time_type_rcd = 'CO'
update date_time_type_ref set date_time_type_name = 'Sjekk inn påminnelse' where date_time_type_rcd = 'CR'
update date_time_type_ref set date_time_type_name = 'Opprettet' where date_time_type_rcd = 'CRE'
update date_time_type_ref set date_time_type_name = 'Sendt' where date_time_type_rcd = 'DP'
update date_time_type_ref set date_time_type_name = 'Estimert ankomst' where date_time_type_rcd = 'EA'
update date_time_type_ref set date_time_type_name = 'Estimert avgang' where date_time_type_rcd = 'ED'
update date_time_type_ref set date_time_type_name = 'Fly fløyet' where date_time_type_rcd = 'FF'
update date_time_type_ref set date_time_type_name = 'Inaktivert' where date_time_type_rcd = 'IA'
update date_time_type_ref set date_time_type_name = 'Låst' where date_time_type_rcd = 'LOC'
update date_time_type_ref set date_time_type_name = 'Laster inn' where date_time_type_rcd = 'LOI'
update date_time_type_ref set date_time_type_name = 'Lasting av' where date_time_type_rcd = 'LOO'
update date_time_type_ref set date_time_type_name = 'Planlagt ankomst' where date_time_type_rcd = 'PA'
update date_time_type_ref set date_time_type_name = 'Planlagt avgang' where date_time_type_rcd = 'PD'
update date_time_type_ref set date_time_type_name = 'Pfs' where date_time_type_rcd = 'PFS'
update date_time_type_ref set date_time_type_name = 'Passasjer navneliste' where date_time_type_rcd = 'PNL'
update date_time_type_ref set date_time_type_name = 'Prl' where date_time_type_rcd = 'PRL'
update date_time_type_ref set date_time_type_name = 'Tilbakestille' where date_time_type_rcd = 'RE'
update date_time_type_ref set date_time_type_name = 'Touchdown' where date_time_type_rcd = 'TD'
update date_time_type_ref set date_time_type_name = 'Takeoff' where date_time_type_rcd = 'TO'
update default_change_log_type_ref set default_change_log_type_name = 'Endret Feature' where default_change_log_type_rcd = 'Change'
update default_change_log_type_ref set default_change_log_type_name = 'Problemet' where default_change_log_type_rcd = 'Issue'
update default_change_log_type_ref set default_change_log_type_name = 'Ny funksjon' where default_change_log_type_rcd = 'New'
update default_change_log_type_ref set default_change_log_type_name = 'Fjernet Feature' where default_change_log_type_rcd = 'Removed'
update default_error_layer_ref set default_error_layer_name = 'Forretningslogikk-lag' where default_error_layer_rcd = 'BLL'
update default_error_layer_ref set default_error_layer_name = 'Business Layer-motor' where default_error_layer_rcd = 'BLLEngine'
update default_error_layer_ref set default_error_layer_name = 'Business Logic Layer rest' where default_error_layer_rcd = 'BLLRest'
update default_error_layer_ref set default_error_layer_name = 'Business Logic Layer såpe' where default_error_layer_rcd = 'BLLSoap'
update default_error_layer_ref set default_error_layer_name = 'Klient motor' where default_error_layer_rcd = 'CEngine'
update default_error_layer_ref set default_error_layer_name = 'Database' where default_error_layer_rcd = 'DB'
update default_error_layer_ref set default_error_layer_name = 'Data tilgangs lag' where default_error_layer_rcd = 'DLL'
update default_error_layer_ref set default_error_layer_name = 'Dokumentasjon' where default_error_layer_rcd = 'DOC'
update default_error_layer_ref set default_error_layer_name = 'Kontroller for ASP-modell visning' where default_error_layer_rcd = 'MVC'
update default_error_layer_ref set default_error_layer_name = 'Klient-proxy' where default_error_layer_rcd = 'Proxy'
update default_error_layer_ref set default_error_layer_name = 'Sql2Wcf' where default_error_layer_rcd = 'S2W'
update default_error_layer_ref set default_error_layer_name = 'Automatisert testing' where default_error_layer_rcd = 'Test'
update default_error_layer_ref set default_error_layer_name = 'Test front' where default_error_layer_rcd = 'TestF'
update default_error_layer_ref set default_error_layer_name = 'Windows-WinForms' where default_error_layer_rcd = 'WinForms'
update default_error_type_ref set default_error_type_name = 'Motoren' where default_error_type_rcd = 'Engine'
update default_error_type_ref set default_error_type_name = 'Lydløs/fanget' where default_error_type_rcd = 'Silent'
update default_error_type_ref set default_error_type_name = 'Automatisert test' where default_error_type_rcd = 'Test'
update default_error_type_ref set default_error_type_name = 'Bruker startet' where default_error_type_rcd = 'User'
update default_issue_status_ref set default_issue_status_name = 'Ikke et problem' where default_issue_status_rcd = 'NotAnIssue'
update default_issue_status_ref set default_issue_status_name = 'Ikke reproduserbar' where default_issue_status_rcd = 'NotReproducible'
update default_issue_status_ref set default_issue_status_name = 'Løst' where default_issue_status_rcd = 'Resolved'
update default_issue_status_ref set default_issue_status_name = 'Skal løses' where default_issue_status_rcd = 'ToBeResolved'
update default_issue_type_ref set default_issue_type_name = 'Bug' where default_issue_type_rcd = 'Bug'
update default_issue_type_ref set default_issue_type_name = 'Endre forespørsel' where default_issue_type_rcd = 'Change'
update default_issue_type_ref set default_issue_type_name = 'Feil oppførsel' where default_issue_type_rcd = 'Incorrect'
update default_issue_type_ref set default_issue_type_name = 'Feature forespørsel' where default_issue_type_rcd = 'Request'
update default_rule_type_ref set default_rule_type_name = 'Skjul lag adresse' where default_rule_type_rcd = 'Hide'
update default_state_ref set default_state_name = 'Opprettet' where default_state_rcd = 'C'
update default_state_ref set default_state_name = 'Ugyldig' where default_state_rcd = 'I'
update default_state_ref set default_state_name = 'Oppdatert' where default_state_rcd = 'U'
update default_system_setting_ref set default_system_setting_name = 'Booking costcentre' where default_system_setting_rcd = 'BCC'
update default_system_setting_ref set default_system_setting_name = 'Booking valuta' where default_system_setting_rcd = 'BCU'
update default_system_setting_ref set default_system_setting_name = 'Mørkt fargevalg' where default_system_setting_rcd = 'dcs'
update default_system_setting_ref set default_system_setting_name = 'e-postadresse' where default_system_setting_rcd = 'EURL'
update default_test_run_result_ref set default_test_run_result_name = 'ok' where default_test_run_result_rcd = 'OK'
update default_test_run_result_ref set default_test_run_result_name = 'Unntak' where default_test_run_result_rcd = 'EX'
update default_test_run_result_ref set default_test_run_result_name = 'Web-unntak' where default_test_run_result_rcd = 'WEBEX'
update default_user_activity_type_ref set default_user_activity_type_name = 'Business Logic-metode startet' where default_user_activity_type_rcd = 'blmi'
update default_user_activity_type_ref set default_user_activity_type_name = 'Skjema åpnet' where default_user_activity_type_rcd = 'fo'
update default_user_activity_type_ref set default_user_activity_type_name = 'Pålogging' where default_user_activity_type_rcd = 'li'
update default_user_activity_type_ref set default_user_activity_type_name = 'Logout' where default_user_activity_type_rcd = 'lo'
update default_user_activity_type_ref set default_user_activity_type_name = 'Planlagt hendelse' where default_user_activity_type_rcd = 'se'
update default_user_activity_type_ref set default_user_activity_type_name = 'Webside åpnet' where default_user_activity_type_rcd = 'wpo'
update ferry_type_ref set ferry_type_name = 'Lastebil' where ferry_type_rcd = 'LO'
update ferry_type_ref set ferry_type_name = 'Bil ferge' where ferry_type_rcd = 'SF'
update financial_adjustment_type_ref set financial_adjustment_type_name = 'Regel for avrunding' where financial_adjustment_type_rcd = 'RR'
update financial_bank_account_number_type_ref set financial_bank_account_number_type_name = 'Internasjonal bank konto' where financial_bank_account_number_type_rcd = 'IBAN'
update financial_bank_account_number_type_ref set financial_bank_account_number_type_name = 'Samfunn over hele verden finansiell telekommunikasjon' where financial_bank_account_number_type_rcd = 'SWIFT'
update financial_booking_transaction_type_ref set financial_booking_transaction_type_name = 'Lagt' where financial_booking_transaction_type_rcd = 'ADD'
update financial_booking_transaction_type_ref set financial_booking_transaction_type_name = 'Fjernet' where financial_booking_transaction_type_rcd = 'REMOVE'
update financial_card_type_ref set financial_card_type_name = 'Amerikansk Ekspress' where financial_card_type_rcd = 'AmEx'
update financial_card_type_ref set financial_card_type_name = 'Master-kort' where financial_card_type_rcd = 'Master'
update financial_card_type_ref set financial_card_type_name = 'Visa' where financial_card_type_rcd = 'Visa'
update financial_coupon_type_ref set financial_coupon_type_name = 'Lounge kupongen' where financial_coupon_type_rcd = 'LC'
update financial_coupon_type_ref set financial_coupon_type_name = 'Måltid kupongen' where financial_coupon_type_rcd = 'MC'
update financial_currency_type_ref set financial_currency_type_name = 'Euro' where financial_currency_type_rcd = 'EUR'
update financial_currency_type_ref set financial_currency_type_name = 'Norwegian Krone' where financial_currency_type_rcd = 'NOK'
update financial_currency_type_ref set financial_currency_type_name = 'Svenske kroner' where financial_currency_type_rcd = 'SEK'
update financial_currency_type_ref set financial_currency_type_name = 'Thailandsk bad' where financial_currency_type_rcd = 'THB'
update financial_currency_type_ref set financial_currency_type_name = 'Amerikanske dollar' where financial_currency_type_rcd = 'USD'
update financial_fare_type_ref set financial_fare_type_name = 'Standard ikke' where financial_fare_type_rcd = 'STD'
update financial_fee_type_ref set financial_fee_type_name = 'Agency Fee' where financial_fee_type_rcd = 'Agency'
update financial_fee_type_ref set financial_fee_type_name = 'Booking Fee' where financial_fee_type_rcd = 'Booking'
update financial_fee_type_ref set financial_fee_type_name = 'Betaling Fee' where financial_fee_type_rcd = 'Payment'
update financial_fee_type_ref set financial_fee_type_name = 'Ekstra service avgift' where financial_fee_type_rcd = 'SSR'
update financial_fee_type_ref set financial_fee_type_name = 'Billett avgift' where financial_fee_type_rcd = 'Ticket'
update financial_payment_type_ref set financial_payment_type_name = 'Regnskap' where financial_payment_type_rcd = 'ACC'
update financial_payment_type_ref set financial_payment_type_name = 'Bank' where financial_payment_type_rcd = 'BANK'
update financial_payment_type_ref set financial_payment_type_name = 'Kort' where financial_payment_type_rcd = 'CARD'
update financial_payment_type_ref set financial_payment_type_name = 'Kontanter' where financial_payment_type_rcd = 'CASH'
update financial_payment_type_ref set financial_payment_type_name = 'Kupong' where financial_payment_type_rcd = 'COUPON'
update financial_payment_type_ref set financial_payment_type_name = 'Standard betaling' where financial_payment_type_rcd = 'STD'
update financial_payment_type_ref set financial_payment_type_name = 'Bilaget' where financial_payment_type_rcd = 'VOU'
update financial_tax_type_ref set financial_tax_type_name = 'Agency skatt' where financial_tax_type_rcd = 'Agency'
update financial_tax_type_ref set financial_tax_type_name = 'Booking skatt' where financial_tax_type_rcd = 'Booking'
update financial_tax_type_ref set financial_tax_type_name = 'Betaling skatt' where financial_tax_type_rcd = 'Payment'
update financial_tax_type_ref set financial_tax_type_name = 'Spesiell tjenesteavgift' where financial_tax_type_rcd = 'SSR'
update financial_tax_type_ref set financial_tax_type_name = 'Billett avgift' where financial_tax_type_rcd = 'Ticket'
update financial_voucher_type_ref set financial_voucher_type_name = 'Bilag for avbrudd' where financial_voucher_type_rcd = 'DV'
update financial_voucher_type_ref set financial_voucher_type_name = 'Flykupong' where financial_voucher_type_rcd = 'FV'
update flight_identifier_type_ref set flight_identifier_type_name = 'Flynummer to' where flight_identifier_type_rcd = 'FN2'
update flight_identifier_type_ref set flight_identifier_type_name = 'Flynummer tre' where flight_identifier_type_rcd = 'FN3'
update flight_identifier_type_ref set flight_identifier_type_name = 'Matriculation' where flight_identifier_type_rcd = 'MATRI'
update flight_schedule_segment_rule_ref set flight_schedule_segment_rule_name = 'Ikke på fredag' where flight_schedule_segment_rule_rcd = 'NoFriday'
update flight_schedule_segment_rule_ref set flight_schedule_segment_rule_name = 'Ikke på mandag' where flight_schedule_segment_rule_rcd = 'NoMonday'
update flight_schedule_segment_rule_ref set flight_schedule_segment_rule_name = 'Ikke på lørdag' where flight_schedule_segment_rule_rcd = 'NoSaturday'
update flight_schedule_segment_rule_ref set flight_schedule_segment_rule_name = 'Ikke på søndag' where flight_schedule_segment_rule_rcd = 'NoSunday'
update flight_schedule_segment_rule_ref set flight_schedule_segment_rule_name = 'Ikke på torsdag' where flight_schedule_segment_rule_rcd = 'NoThursday'
update flight_schedule_segment_rule_ref set flight_schedule_segment_rule_name = 'Ikke på tirsdag' where flight_schedule_segment_rule_rcd = 'NoTuesday'
update flight_schedule_segment_rule_ref set flight_schedule_segment_rule_name = 'Ikke på onsdag' where flight_schedule_segment_rule_rcd = 'NoWednesday'
update gender_ref set gender_name = 'Kvinnelige' where gender_rcd = 'F'
update gender_ref set gender_name = 'Mannlige' where gender_rcd = 'M'
update language_ref set language_name = 'Engelsk' where language_rcd = 'en-US'
update language_ref set language_name = 'Norsk Bokmål' where language_rcd = 'nb-NO'
update language_ref set language_name = '???????' where language_rcd = 'th-TH'
update link_type_ref set link_type_name = 'Sosiale medier' where link_type_rcd = 'SM'
update link_type_ref set link_type_name = 'Webområde' where link_type_rcd = 'WS'
update nationality_ref set nationality_name = 'Jupiter' where nationality_rcd = 'JU'
update nationality_ref set nationality_name = 'Mars' where nationality_rcd = 'MA'
update passenger_type_ref set passenger_type_name = 'Voksen' where passenger_type_rcd = 'AD'
update passenger_type_ref set passenger_type_name = 'Barn' where passenger_type_rcd = 'CHD'
update passenger_type_ref set passenger_type_name = 'Spedbarn' where passenger_type_rcd = 'INF'
update reporting_roundup_type_ref set reporting_roundup_type_name = 'Bestillinger per dag' where reporting_roundup_type_rcd = 'Bookings'
update reporting_roundup_type_ref set reporting_roundup_type_name = 'Bestilling passasjer' where reporting_roundup_type_rcd = 'BP'
update service_image_type_ref set service_image_type_name = 'Internt Stock-bilde' where service_image_type_rcd = 'ISP'
update service_image_type_ref set service_image_type_name = 'Variabel størrelse for produktbilde' where service_image_type_rcd = 'PI'
update service_request_status_ref set service_request_status_name = 'SSR har blitt bekreftet' where service_request_status_rcd = 'HK'
update service_request_status_ref set service_request_status_name = 'SSR har blitt forespurt' where service_request_status_rcd = 'NN'
update service_request_status_ref set service_request_status_name = 'Andre' where service_request_status_rcd = 'OTHER'
update service_request_status_ref set service_request_status_name = 'SSR venter på bekreftelse' where service_request_status_rcd = 'PN'
update service_request_status_ref set service_request_status_name = 'Fjernet' where service_request_status_rcd = 'REM'
update service_request_status_ref set service_request_status_name = 'Transportøren kan ikke fullføre forespørselen' where service_request_status_rcd = 'UN'
update service_special_service_request_group_ref set service_special_service_request_group_name = 'Ingen' where service_special_service_request_group_rcd = 'None'
update service_special_service_request_operation_rule_ref set service_special_service_request_operation_rule_name = 'Manuell' where service_special_service_request_operation_rule_rcd = 'MAN'
update service_special_service_request_operation_rule_ref set service_special_service_request_operation_rule_name = 'Programmatisk' where service_special_service_request_operation_rule_rcd = 'PRO'
update service_special_service_request_requirement_ref set service_special_service_request_requirement_name = 'Ingen' where service_special_service_request_requirement_rcd = 'N'
update service_special_service_request_requirement_ref set service_special_service_request_requirement_name = 'Valgfritt' where service_special_service_request_requirement_rcd = 'O'
update service_special_service_request_requirement_ref set service_special_service_request_requirement_name = 'Nødvendig' where service_special_service_request_requirement_rcd = 'R'
update service_type_ref set service_type_name = 'Leiebil' where service_type_rcd = 'CR'
update service_type_ref set service_type_name = 'Ferge Booking' where service_type_rcd = 'FE'
update service_type_ref set service_type_name = 'Hotell Booking' where service_type_rcd = 'HB'
update service_type_ref set service_type_name = 'Spesielle tjenester' where service_type_rcd = 'SS'
update title_ref set title_name = 'Mr.' where title_rcd = 'MR'
update title_ref set title_name = 'Ms.' where title_rcd = 'MS'
                            ",
                    BreakUpToBatches = true
                }
                #endregion
            });


        }
    }
}
