/*
  SQL2X Generated code based on a SQL Server Schema
  SQL2X Version: 1.0
  http://sql2x.org/
  Generated Date: 12/28/2020 12:49:35 AM
  From Machine: DESKTOP-BP3OHLH
  Template: sql2x.ProxyGenerator.ProxyForMethodNewStyle
*/
using System.Collections.Generic;
namespace SolutionNorSolutionPort.BusinessLogicLayer {

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAirlineSearchService")]
    public interface IAirlineSearchService {
        // transfer all objects from data to contract
        // links:
        //  docLink: http://sql2x.org/documentationLink/da04228c-8663-4aa2-b0ba-64712bbdc601
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirlineSearchService/AirlineIdentifierIndexWithFilter", ReplyAction="http://tempuri.org/IAirlineSearchService/AirlineIdentifierIndexWithFilterResponse")]
        List<AirlineIdentifierIndexWithFilterContract> AirlineIdentifierIndexWithFilter ();
        // transfer all objects from data to contract
        // links:
        //  docLink: http://sql2x.org/documentationLink/da04228c-8663-4aa2-b0ba-64712bbdc601
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirlineSearchService/GetAirlineIndexWithFilter", ReplyAction="http://tempuri.org/IAirlineSearchService/GetAirlineIndexWithFilterResponse")]
        List<GetAirlineIndexWithFilterContract> GetAirlineIndexWithFilter ();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAirlineSearchServiceChannel : IAirlineSearchService, System.ServiceModel.IClientChannel {
    }
    
    public class AirlineSearchService : System.ServiceModel.ClientBase<IAirlineSearchService>, IAirlineSearchService {
        // This Method
        // is generated by
        // links:
        //  SQL2X.org: https://sql2.org
        //  docLink: http://sql2x.org/documentationLink/3cf57883-f68e-4318-80a4-1a36604ef84b
        public List<AirlineIdentifierIndexWithFilterContract> AirlineIdentifierIndexWithFilter () {
            return base.Channel.AirlineIdentifierIndexWithFilter();
        }
        // This Method
        // is generated by
        // links:
        //  SQL2X.org: https://sql2.org
        //  docLink: http://sql2x.org/documentationLink/3cf57883-f68e-4318-80a4-1a36604ef84b
        public List<GetAirlineIndexWithFilterContract> GetAirlineIndexWithFilter () {
            return base.Channel.GetAirlineIndexWithFilter();
        }
        
        public AirlineSearchService() {
        }
        
        public AirlineSearchService(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirlineSearchService(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirlineSearchService(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirlineSearchService(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
}
