/*
  SQL2X Generated code based on a SQL Server Schema
  SQL2X Version: 1.0
  http://sql2x.org/
  Generated Date: 12/28/2020 5:20:43 PM
  From Machine: DESKTOP-LSRVP12
  Template: sql2x.ProxyGenerator.ProxyForMethodNewStyle
*/
using System.Collections.Generic;
namespace SolutionNorSolutionPort.BusinessLogicLayer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAircraftMaintenanceSearchService")]
    public interface IAircraftMaintenanceSearchService {
        // transfer all objects from data to contract
        // links:
        //  docLink: http://sql2x.org/documentationLink/da04228c-8663-4aa2-b0ba-64712bbdc601
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftPIMDetails", ReplyAction="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftPIMDetailsResponse")]
        List<AircraftPIMDetailsContract> AircraftPIMDetails ();
        // transfer all objects from data to contract
        // links:
        //  docLink: http://sql2x.org/documentationLink/da04228c-8663-4aa2-b0ba-64712bbdc601
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftMaintenanceIndexWithFilter", ReplyAction="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftMaintenanceIndexWithFilterResponse")]
        List<AircraftMaintenanceIndexWithFilterContract> AircraftMaintenanceIndexWithFilter ();
        // transfer all objects from data to contract
        // links:
        //  docLink: http://sql2x.org/documentationLink/da04228c-8663-4aa2-b0ba-64712bbdc601
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftMaintenanceCompartmentIndexWithFilter", ReplyAction="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftMaintenanceCompartmentIndexWithFilterResponse")]
        List<AircraftMaintenanceCompartmentIndexWithFilterContract> AircraftMaintenanceCompartmentIndexWithFilter (System.Guid aircraftId);
        // transfer all objects from data to contract
        // links:
        //  docLink: http://sql2x.org/documentationLink/da04228c-8663-4aa2-b0ba-64712bbdc601
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftMaintenanceIdentifierIndexWithFilter", ReplyAction="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftMaintenanceIdentifierIndexWithFilterResponse")]
        List<AircraftMaintenanceIdentifierIndexWithFilterContract> AircraftMaintenanceIdentifierIndexWithFilter (System.Guid aircraftId);
        // transfer all objects from data to contract
        // links:
        //  docLink: http://sql2x.org/documentationLink/da04228c-8663-4aa2-b0ba-64712bbdc601
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftMaintenanceDocumentIndexWithFilter", ReplyAction="http://tempuri.org/IAircraftMaintenanceSearchService/AircraftMaintenanceDocumentIndexWithFilterResponse")]
        List<AircraftMaintenanceDocumentIndexWithFilterContract> AircraftMaintenanceDocumentIndexWithFilter (System.Guid aircraftId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAircraftMaintenanceSearchServiceChannel : IAircraftMaintenanceSearchService, System.ServiceModel.IClientChannel {
    }
    
    public class AircraftMaintenanceSearchService : System.ServiceModel.ClientBase<IAircraftMaintenanceSearchService>, IAircraftMaintenanceSearchService {
        // This Method
        // is generated by
        // links:
        //  SQL2X.org: https://sql2.org
        //  docLink: http://sql2x.org/documentationLink/3cf57883-f68e-4318-80a4-1a36604ef84b
        public List<AircraftPIMDetailsContract> AircraftPIMDetails () {
            return base.Channel.AircraftPIMDetails();
        }
        // This Method
        // is generated by
        // links:
        //  SQL2X.org: https://sql2.org
        //  docLink: http://sql2x.org/documentationLink/3cf57883-f68e-4318-80a4-1a36604ef84b
        public List<AircraftMaintenanceIndexWithFilterContract> AircraftMaintenanceIndexWithFilter () {
            return base.Channel.AircraftMaintenanceIndexWithFilter();
        }
        // This Method
        // is generated by
        // links:
        //  SQL2X.org: https://sql2.org
        //  docLink: http://sql2x.org/documentationLink/3cf57883-f68e-4318-80a4-1a36604ef84b
        public List<AircraftMaintenanceCompartmentIndexWithFilterContract> AircraftMaintenanceCompartmentIndexWithFilter (System.Guid aircraftId) {
            return base.Channel.AircraftMaintenanceCompartmentIndexWithFilter(aircraftId);
        }
        // This Method
        // is generated by
        // links:
        //  SQL2X.org: https://sql2.org
        //  docLink: http://sql2x.org/documentationLink/3cf57883-f68e-4318-80a4-1a36604ef84b
        public List<AircraftMaintenanceIdentifierIndexWithFilterContract> AircraftMaintenanceIdentifierIndexWithFilter (System.Guid aircraftId) {
            return base.Channel.AircraftMaintenanceIdentifierIndexWithFilter(aircraftId);
        }
        // This Method
        // is generated by
        // links:
        //  SQL2X.org: https://sql2.org
        //  docLink: http://sql2x.org/documentationLink/3cf57883-f68e-4318-80a4-1a36604ef84b
        public List<AircraftMaintenanceDocumentIndexWithFilterContract> AircraftMaintenanceDocumentIndexWithFilter (System.Guid aircraftId) {
            return base.Channel.AircraftMaintenanceDocumentIndexWithFilter(aircraftId);
        }
        
        public AircraftMaintenanceSearchService() {
        }
        
        public AircraftMaintenanceSearchService(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AircraftMaintenanceSearchService(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AircraftMaintenanceSearchService(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AircraftMaintenanceSearchService(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
}
